[build]
rustc-wrapper = "cachepot"
jobs = 8

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-arg=-Xlinker --threads=8",
]
linker = "clang"

[profile.dev]
debug = false
