#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
eww open bar
bspc monitor -d $(seq 9)
bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
~/.config/bspwm/scripts/npt &
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a emacs state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
setxkbmap br
nitrogen --restore
picom -b
bg() {
	pgrep -x "system76-scheduler" || pkexec system76-scheduler daemon 
}

bg & 
