#! /bin/sh


bash ~/.config/bspwm/monitors.sh
bspc config border_width        2
bspc config window_gap          5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


picom --config ~/.config/picom/picom.conf &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
${HOME}/.fehbg
/usr/lib/xfce4/notifyd/xfce4-notifyd &
MONITOR="eDP-0" polybar -c /home/yxqsnz/.config/polybar/config bar &
MONITOR="HDMI-1" polybar -c /home/yxqsnz/.config/polybar/config_monitor_2 sidebar &

