#!/usr/bin/bash
notify() {
	dunstify -h string:hlcolor:#ffd5cd -h int:value:$@ 
}
if [[ "$1" == "change-volume" ]]; then
    case $2 in
		up) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
		down) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;	
	esac
	VOL=`pactl get-sink-volume @DEFAULT_SINK@ | awk '{ print $5 }' | head -n1 | sed 's/%//g'`
	notify $VOL "Sound" 
fi
