#!/bin/sh
export URL=`playerctl metadata --format '{{ mpris:artUrl }}'`
export TITLE=`playerctl metadata --format '{{ title }}'`
export ARTIST=`playerctl metadata --format '{{ artist}}'`
export URL=`echo "${URL##*file://}"`

echo "(box
	  :orientation \"v\" 
	  :class \"status\"
	  :space-evenly false
	 (image :path \"${URL}\")
	 (box 
	 	:orientation \"v\" 
	 	:class \"status-itens\"
	 	(label :wrap true :text \"${TITLE}\")
	 	(label :wrap true :text \"${ARTIST}\")))
"
