#!/bin/sh

calendar() {
  LOCK_FILE="$HOME/.cache/eww-calendar.lock"

  run() {
    eww  open calendar
  }

  # Run eww daemon if not running
  if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
  fi

  # Open widgets
  if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
  else
    eww close calendar
    rm "$LOCK_FILE"
  fi
}

if [ "$1" = "launcher" ]; then
  rofi -show drun
elif [ "$1" = "wifi" ]; then
  kitty --class Net -e nmtui
elif [ "$1" = "audio" ]; then
  pavucontrol
elif [ "$1" = "calendar" ]; then
  calendar
fi
