#! /usr/bin/env bash
export XDG_RUNTIME_DIR="/tmp/user/${UID}/runtime-dir"
mkdir -p $XDG_RUNTIME_DIR

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap          6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config pointer_modifier mod1
bspc config focus_follows_pointer on

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nemo state=floating
bspc rule -a Emacs state=tiled

exec_safe() {
	pgrep $1 || $($@) &
}

exec_safe setxkbmap br,us -option grp:win_space_toggle
exec_safe /usr/lib/cinnamon-settings-daemon/csd-mouse
exec_safe pipewire
exec_safe pipewire-pulse
exec_safe pipewire-media-session
sleep 0.2
#exec_safe polybar
exec_safe picom
exec_safe flashfocus
exec_safe xsetroot -cursor_name left_ptr
exec_safe gnome-keyring-daemon --start --components=secrets
exec_safe /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#xset r rate 300 50
exec_safe ipfs daemon
#exec_safe xrandr --output DisplayPort-1 --mode 1920x1080 --rate 144.00
exec_safe xwallpaper --zoom $(cat $HOME/.cache/wal/wal)
exec_safe xfce4-clipman
exec_safe redshift -l "0:0" -m randr -t 4500K:4500K
exec_safe ~/.config/polybar/launch.sh

