#! /bin/sh
R() {
  pgrep -x "$1" > /dev/null || $@ &
}

bspc monitor -d G O O D B Y E '!' 

bspc config border_width         0
bspc config window_gap           13
bspc config focused_border_color '#45475a'
bspc config normal_border_color  '#313244'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Default
bspc rule -a Gimp desktop=8 state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# XFCE4 - Panel
bspc rule -a xfce4-panel layer=below sticky=off manage=on focus=off border=off locked=on

# Firefox's PiP
bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on \
     rectangle=461x260+2760+1040

# Roblox
bspc rule -a "robloxplayerlauncher.exe" border=off center=on state=floating desktop=4
bspc rule -a "robloxplayerbeta.exe" desktop=4 

# Japanese 
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus
export SDL_IM_MODULE=fcitx
R polybar 

R picom
R nm-applet
R xsetroot -cursor_name arrow
R ~/.fehbg
R xfce4-power-manager
R systemctl start dunst
R fcitx5
R sxhkd
