#! /bin/sh
R() {
  pgrep -x "$@" > /dev/null || $@ &
}

bspc monitor -d G O O D B Y E 

bspc config border_width         1
bspc config window_gap           12
bspc config focused_border_color '#45475a'
bspc config normal_border_color  '#313244'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config bottom_padding 34

R sxhkd
R polybar
R dunst
R xsetroot -cursor_name arrow
R ~/.fehbg
R xfce4-power-manager
