[build]
rustc-wrapper = "sccache"
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Xlinker --threads=4"
]
linker = "clang"
[target.'cfg(debug_assertions)']
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Xlinker --threads=4",
    "-C", "target-cpu=native"
]

