[build]
rustc-wrapper = "sccache"
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Xlinker --threads=4"
]
linker = "clang"
[target.'cfg(all(debug_assertions, target_arch = "x86_64", target_os = "linux"))']
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Xlinker --threads=4",
    "-C", "target-cpu=native"
]

