[build]
rustc-wrapper = "cachepot"
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Xlinker --threads=8"
]
linker = "clang"

[profile.dev]
debug = false

